version: '3.8'

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto AMQP
      - "15672:15672" # Puerto de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  # CockroachDB (Nodo principal)
  cockroachdb-primary:
    image: cockroachdb/cockroach:v23.1.3
    container_name: cockroachdb-primary
    command: start-single-node --insecure
    ports:
      - "26257:26257" # Puerto SQL
      - "8081:8081"   # Puerto de administración
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    networks:
      - app-network

  # CockroachDB (Nodo secundario replicado)
  cockroachdb-secondary:
    image: cockroachdb/cockroach:v23.1.3
    container_name: cockroachdb-secondary
    command: start --insecure --join=cockroachdb-primary
    depends_on:
      - cockroachdb-primary
    networks:
      - app-network

volumes:
  cockroach-data:

networks:
  app-network:
    driver: bridge