version: '3.8'

services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  # CockroachDB Node 1 (Primary)
  cockroachdb-node1:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node1
    command: start --insecure --advertise-addr=cockroachdb-node1 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3
    ports:
      - "26257:26257" # SQL
      - "8080:8080"   # UI
    volumes:
      - cockroach-data-node1:/cockroach/cockroach-data
    networks:
      - app-network

  # CockroachDB Node 2 (Secondary)
  cockroachdb-node2:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node2
    command: start --insecure --advertise-addr=cockroachdb-node2 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3
    ports:
      - "26258:26257" # SQL
      - "8081:8080"   # UI
    volumes:
      - cockroach-data-node2:/cockroach/cockroach-data
    networks:
      - app-network

  # CockroachDB Node 3 (Secondary)
  cockroachdb-node3:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-node3
    command: start --insecure --advertise-addr=cockroachdb-node3 --join=cockroachdb-node1,cockroachdb-node2,cockroachdb-node3
    ports:
      - "26259:26257" # SQL
      - "8082:8080"   # UI
    volumes:
      - cockroach-data-node3:/cockroach/cockroach-data
    networks:
      - app-network

  # CockroachDB Init (Inicialización del Cluster)
  cockroach-init:
    image: cockroachdb/cockroach:latest
    container_name: cockroach-init
    depends_on:
      - cockroachdb-node1
      - cockroachdb-node2
      - cockroachdb-node3
    entrypoint: ["bash", "-c", "sleep 10 && cockroach init --insecure --host=cockroachdb-node1"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cockroach-data-node1:
  cockroach-data-node2:
  cockroach-data-node3:
  rabbitmq_data: