spring:
  datasource:
    url: jdbc:postgresql://localhost:26259/notifications?sslmode=disable
    username: root
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect